In [2]:
import pandas as pd
import seaborn as sns

In [3]:
# Define the headers since the data does not have any
headers = ["symboling", "normalized_losses", "make", "fuel_type", "aspiration",
           "num_doors", "body_style", "drive_wheels", "engine_location",
           "wheel_base", "length", "width", "height", "curb_weight",
           "engine_type", "num_cylinders", "engine_size", "fuel_system",
           "bore", "stroke", "compression_ratio", "horsepower", "peak_rpm",
           "city_mpg", "highway_mpg", "price"]

# Read in the CSV file and convert "?" to NaN
df_raw = pd.read_csv("http://mlr.cs.umass.edu/ml/machine-learning-databases/autos/imports-85.data",
                     header=None, names=headers, na_values="?" )

# Define a list of models that we want to review
models = ["toyota","nissan","mazda", "honda", "mitsubishi", "subaru", "volkswagen", "volvo"]

# Create a copy of the data with only the top 8 manufacturers
df = df_raw[df_raw.make.isin(models)].copy()

In [ ]:
df.transpose()

,30,31,32,33,34,35,36,37,38,39,...,195,196,197,198,199,200,201,202,203,204
symboling,2,2,1,1,1,0,0,0,0,0,...,-1,-2,-1,-2,-1,-1,-1,-1,-1,-1
normalized_losses,137,137,101,101,101,110,78,106,106,85,...,74,103,74,103,74,95,95,95,95,95
make,honda,honda,honda,honda,honda,honda,honda,honda,honda,honda,...,volvo,volvo,volvo,volvo,volvo,volvo,volvo,volvo,volvo,volvo
fuel_type,gas,gas,gas,gas,gas,gas,gas,gas,gas,gas,...,gas,gas,gas,gas,gas,gas,gas,gas,diesel,gas
aspiration,std,std,std,std,std,std,std,std,std,std,...,std,std,std,turbo,turbo,std,turbo,std,turbo,turbo
num_doors,two,two,two,two,two,four,four,two,two,four,...,four,four,four,four,four,four,four,four,four,four
body_style,hatchback,hatchback,hatchback,hatchback,hatchback,sedan,wagon,hatchback,hatchback,sedan,...,wagon,sedan,wagon,sedan,wagon,sedan,sedan,sedan,sedan,sedan
drive_wheels,fwd,fwd,fwd,fwd,fwd,fwd,fwd,fwd,fwd,fwd,...,rwd,rwd,rwd,rwd,rwd,rwd,rwd,rwd,rwd,rwd
engine_location,front,front,front,front,front,front,front,front,front,front,...,front,front,front,front,front,front,front,front,front,front
wheel_base,86.6,86.6,93.7,93.7,93.7,96.5,96.5,96.5,96.5,96.5,...,104.3,104.3,104.3,104.3,104.3,109.1,109.1,109.1,109.1,109.1
length,144.6,144.6,150,150,150,163.4,157.1,167.5,167.5,175.4,...,188.8,188.8,188.8,188.8,188.8,188.8,188.8,188.8,188.8,188.8
width,63.9,63.9,64,64,64,64,63.9,65.2,65.2,65.2,...,67.2,67.2,67.2,67.2,67.2,68.9,68.8,68.9,68.9,68.9
height,50.8,50.8,52.6,52.6,52.6,54.5,58.3,53.3,53.3,54.1,...,57.5,56.2,57.5,56.2,57.5,55.5,55.5,55.5,55.5,55.5
curb_weight,1713,1819,1837,1940,1956,2010,2024,2236,2289,2304,...,3034,2935,3042,3045,3157,2952,3049,3012,3217,3062
engine_type,ohc,ohc,ohc,ohc,ohc,ohc,ohc,ohc,ohc,ohc,...,ohc,ohc,ohc,ohc,ohc,ohc,ohc,ohcv,ohc,ohc
num_cylinders,four,four,four,four,four,four,four,four,four,four,...,four,four,four,four,four,four,four,six,six,four
engine_size,92,92,79,92,92,92,92,110,110,110,...,141,141,141,130,130,141,141,173,145,141
fuel_system,1bbl,1bbl,1bbl,1bbl,1bbl,1bbl,1bbl,1bbl,1bbl,1bbl,...,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,idi,mpfi
bore,2.91,2.91,2.91,2.91,2.91,2.91,2.92,3.15,3.15,3.15,...,3.78,3.78,3.78,3.62,3.62,3.78,3.78,3.58,3.01,3.78
stroke,3.41,3.41,3.07,3.41,3.41,3.41,3.41,3.58,3.58,3.58,...,3.15,3.15,3.15,3.15,3.15,3.15,3.15,2.87,3.4,3.15
compression_ratio,9.6,9.2,10.1,9.2,9.2,9.2,9.2,9,9,9,...,9.5,9.5,9.5,7.5,7.5,9.5,8.7,8.8,23,9.5
horsepower,58,76,60,76,76,76,76,86,86,86,...,114,114,114,162,162,114,160,134,106,114
peak_rpm,4800,6000,5500,6000,6000,6000,6000,5800,5800,5800,...,5400,5400,5400,5100,5100,5400,5300,5500,4800,5400
city_mpg,49,31,38,30,30,30,30,27,27,27,...,23,24,24,17,17,23,19,18,26,19
highway_mpg,54,38,42,34,34,34,34,33,33,33,...,28,28,28,22,22,28,25,23,27,25
price,6479,6855,5399,6529,7129,7295,7295,7895,9095,8845,...,13415,15985,16515,18420,18950,16845,19045,21485,22470,22625

In [5]:
pd.crosstab(df.make, df.body_style)

body_style  convertible  hardtop  hatchback  sedan  wagon
make
honda                 0        0          7      5      1
mazda                 0        0         10      7      0
mitsubishi            0        0          9      4      0
nissan                0        1          5      9      3
subaru                0        0          3      5      4
toyota                1        3         14     10      4
volkswagen            1        0          1      9      1
volvo                 0        0          0      8      3